% Información básica de las plantas
planta(ajo, 'Allium sativum').
planta(borraja, 'Borago officinalis').
planta(bugambilia, 'Bougainvillea spectabilis').
planta(brionia_blanca, 'Bryonia alba').
planta(ahuehuete, 'Taxodium mucronatum').
planta(ajenjo, 'Artemisia absinthium').
planta(pasiflora, 'Passiflora incarnata').
planta(palo_de_flor, 'Plumeria rubra').
planta(oregano, 'Origanum vulgare').
planta(ortiga, 'Urtica urens').
planta(anis_estrella, 'Illicium verum').
planta(menta, 'Mentha spicata').
planta(arnica, 'Arnica montana').
planta(salvia, 'Salvia officinalis').
planta(tila, 'Tilia platyphyllos').
planta(eucalipto, 'Eucalyptus globulus').
planta(yerbabuena, 'Mentha spicata').
planta(manzanilla, 'Matricaria chamomilla').
planta(cola_de_caballo, 'Equisetum arvense').
planta(romero, 'Rosmarinus officinalis').
planta(toronjil, 'Melissa officinalis').
planta(sanguinaria, 'Sanguinaria canadensis').
planta(linaza, 'Linum usitatissimum').
planta(hamamelis, 'Hamamelis virginiana').
planta(zarzaparrilla, 'Smilax aspera').
planta(boldo, 'Peumus boldus').
planta(diente_de_leon, 'Taraxacum officinale').
planta(azahar, 'Citrus aurantium').
planta(malva, 'Malva sylvestris').
planta(marrubio, 'Marrubium vulgare').
planta(rosal, 'Rosa spp.').

% Elementos contenidos
elemento(ajo, allicina).
elemento(ajo, vitamina_b6).
elemento(ajo, vitamina_c).
elemento(ajo, manganeso).
elemento(ajo, selenio).
elemento(ajo, fibra).
elemento(borraja, acidos_grasos_esenciales).
elemento(borraja, gla).
elemento(borraja, alcaloides).
elemento(borraja, flavonoides).
elemento(borraja, vitamina_c).
elemento(bugambilia, flavonoides).
elemento(bugambilia, saponinas).
elemento(bugambilia, taninos).
elemento(bugambilia, alcaloides).
elemento(brionia_blanca, glucosidos).
elemento(brionia_blanca, resinas).
elemento(brionia_blanca, saponinas).
elemento(brionia_blanca, alcaloides).
elemento(ahuehuete, taninos).
elemento(ahuehuete, resinas).
elemento(ahuehuete, aceites_esenciales).
elemento(ajenjo, absinina).
elemento(ajenjo, tujona).
elemento(ajenjo, flavonoides).
elemento(ajenjo, taninos).
elemento(pasiflora, flavonoides).
elemento(pasiflora, alcaloides).
elemento(pasiflora, compuestos_fenolicos).
elemento(pasiflora, saponinas).
elemento(palo_de_flor, latex).
elemento(palo_de_flor, alcaloides).
elemento(palo_de_flor, compuestos_fenolicos).
elemento(palo_de_flor, flavonoides).
elemento(oregano, aceites_esenciales).
elemento(oregano, carvacrol).
elemento(oregano, timol).
elemento(oregano, flavonoides).
elemento(oregano, acidos_fenolicos).
elemento(oregano, vitamina_k).
elemento(oregano, calcio).
elemento(oregano, magnesio).
elemento(oregano, hierro).
elemento(ortiga, acido_formico).
elemento(ortiga, histamina).
elemento(ortiga, clorofila).
elemento(ortiga, taninos).
elemento(ortiga, hierro).
elemento(ortiga, calcio).
elemento(ortiga, vitamina_a).
elemento(ortiga, vitamina_c).
elemento(ortiga, vitamina_k).
elemento(anis_estrella, anetol).
elemento(anis_estrella, safrol).
elemento(anis_estrella, cineol).
elemento(anis_estrella, estragol).
elemento(menta, mentol).
elemento(menta, carvona).
elemento(menta, limoneno).
elemento(arnica, helenalina).
elemento(arnica, flavonoides).
elemento(arnica, cumarinas).
elemento(salvia, ácido_rosemarínico).
elemento(salvia, cineol).
elemento(salvia, tujona).
elemento(tila, flavonoides).
elemento(tila, aceites_esenciales).
elemento(eucalipto, cineol).
elemento(eucalipto, taninos).
elemento(eucalipto, flavonoides).
elemento(yerbabuena, mentol).
elemento(yerbabuena, carvona).
elemento(yerbabuena, limoneno).
elemento(manzanilla, camazuleno).
elemento(manzanilla, alfa-bisabolol).
elemento(manzanilla, flavonoides).
elemento(cola_de_caballo, sílice).
elemento(cola_de_caballo, flavonoides).
elemento(cola_de_caballo, alcaloides).
elemento(romero, ácido_rosmarínico).
elemento(romero, cineol).
elemento(romero, pineno).
elemento(toronjil, ácido_rosmarínico).
elemento(toronjil, citronelal).
elemento(toronjil, geraniol).
elemento(sanguinaria, alcaloides).
elemento(sanguinaria, sanguinarina).
elemento(linaza, ácidos_grasos_omega-3).
elemento(linaza, lignanos).
elemento(linaza, fibra).
elemento(hamamelis, taninos).
elemento(hamamelis, flavonoides).
elemento(hamamelis, aceites_esenciales).
elemento(zarzaparrilla, saponinas).
elemento(zarzaparrilla, fitosteroles).
elemento(zarzaparrilla, flavonoides).
elemento(boldo, boldina).
elemento(boldo, aceites_esenciales).
elemento(diente_de_leon, inulina).
elemento(diente_de_leon, taraxacina).
elemento(diente_de_leon, flavonoides).
elemento(azahar, linalol).
elemento(azahar, limoneno).
elemento(azahar, flavonoides).
elemento(malva, mucílagos).
elemento(malva, antocianinas).
elemento(malva, flavonoides).
elemento(marrubio, marrubiina).
elemento(marrubio, taninos).
elemento(marrubio, flavonoides).
elemento(rosal, vitamina_C).
elemento(rosal, flavonoides).
elemento(rosal, taninos).
elemento(achicoria, inulina).
elemento(achicoria, lactonas).
elemento(achicoria, vitaminas).
elemento(alcachofa, cinarina).
elemento(alcachofa, ácidos_fenólicos).
elemento(alcachofa, flavonoides).
elemento(anis, anetol).
elemento(anis, flavonoides).
elemento(anis, aceites_esenciales).
elemento(canela, cinamaldehído).
elemento(canela, eugenol).
elemento(canela, taninos).
elemento(cedron, citral).
elemento(cedron, limoneno).
elemento(cedron, flavonoides).
elemento(enebro, terpenos).
elemento(enebro, flavonoides).
elemento(enebro, aceites_esenciales).
elemento(fenogreco, saponinas).
elemento(fenogreco, alcaloides).
elemento(fenogreco, fibras).
elemento(fumaria, alcaloides).
elemento(fumaria, flavonoides).
elemento(fumaria, taninos).
elemento(hierbabuena, mentol).
elemento(hierbabuena, carvona).
elemento(hierbabuena, limoneno).
elemento(jengibre, gingerol).
elemento(jengibre, shogaol).
elemento(jengibre, zingibereno).
elemento(lavanda, linalol).
elemento(lavanda, cineol).
elemento(lavanda, alcanfor).
elemento(naranjo, vitamina_C).
elemento(naranjo, flavonoides).
elemento(naranjo, limoneno).
elemento(perejil, vitamina_C).
elemento(perejil, flavonoides).
elemento(perejil, apigenina).
elemento(sabila, aloína).
elemento(sabila, acemanano).
elemento(sabila, vitaminas).
elemento(valeriana, ácido_valerénico).
elemento(valeriana, flavonoides).
elemento(valeriana, aceites_esenciales).

% Medicamentos producidos
medicamento(ajo, suplementos_de_ajo).
medicamento(ajo, aceites_esenciales).
medicamento(ajo, extractos_de_ajo).
medicamento(borraja, aceite_de_borraja).
medicamento(borraja, infusiones).
medicamento(borraja, capsulas).
medicamento(bugambilia, jarabe_de_bugambilia).
medicamento(bugambilia, infusiones).
medicamento(bugambilia, extractos).
medicamento(brionia_blanca, extracto_de_brionia).
medicamento(brionia_blanca, tintura).
medicamento(brionia_blanca, unguentos).
medicamento(ahuehuete, infusiones).
medicamento(ahuehuete, extractos).
medicamento(ahuehuete, unguentos).
medicamento(ajenjo, extracto_de_ajenjo).
medicamento(ajenjo, infusiones).
medicamento(ajenjo, tinturas).
medicamento(pasiflora, extracto_de_pasiflora).
medicamento(pasiflora, infusiones).
medicamento(pasiflora, capsulas).
medicamento(palo_de_flor, aceite_de_palo_de_flor).
medicamento(palo_de_flor, extractos).
medicamento(palo_de_flor, unguentos).
medicamento(oregano, aceite_de_oregano).
medicamento(oregano, extracto_de_oregano).
medicamento(oregano, infusiones).
medicamento(ortiga, suplementos_de_ortiga).
medicamento(ortiga, extractos_de_ortiga).
medicamento(ortiga, cremas_de_ortiga).
medicamento(anis_estrella, aceite_esencial_de_anis_estrella).
medicamento(anis_estrella, infusiones).
medicamento(anis_estrella, extractos).
medicamento(menta, aceite_esencial_de_menta).
medicamento(menta, infusiones).
medicamento(arnica, cremas).
medicamento(arnica, ungüentos).
medicamento(salvia, aceite_esencial).
medicamento(salvia, extractos).
medicamento(tila, infusiones).
medicamento(tila, extractos).
medicamento(eucalipto, aceite_esencial).
medicamento(eucalipto, infusiones).
medicamento(yerbabuena, aceite_esencial).
medicamento(yerbabuena, infusiones).
medicamento(manzanilla, infusiones).
medicamento(manzanilla, extractos).
medicamento(cola_de_caballo, infusiones).
medicamento(cola_de_caballo, extractos).
medicamento(romero, aceite_esencial).
medicamento(romero, infusiones).
medicamento(toronjil, infusiones).
medicamento(toronjil, extractos).
medicamento(sanguinaria, extractos).
medicamento(sanguinaria, tinturas).
medicamento(linaza, aceite_de_linaza).
medicamento(linaza, suplementos).
medicamento(hamamelis, extracto_de_hamamelis).
medicamento(hamamelis, cremas).
medicamento(zarzaparrilla, extractos).
medicamento(zarzaparrilla, infusiones).
medicamento(boldo, infusiones).
medicamento(boldo, extractos).
medicamento(diente_de_leon, infusiones).
medicamento(diente_de_leon, extractos).
medicamento(azahar, infusiones).
medicamento(azahar, extractos).
medicamento(malva, infusiones).
medicamento(malva, extractos).
medicamento(marrubio, infusiones).
medicamento(marrubio, extractos).
medicamento(rosal, infusiones).
medicamento(rosal, extractos).
medicamento(achicoria, infusiones).
medicamento(achicoria, extractos).
medicamento(alcachofa, infusiones).
medicamento(alcachofa, extractos).
medicamento(anis, infusiones).
medicamento(anis, extractos).
medicamento(canela, infusiones).
medicamento(canela, extractos).
medicamento(cedron, infusiones).
medicamento(cedron, extractos).
medicamento(enebro, infusiones).
medicamento(enebro, extractos).
medicamento(fenogreco, infusiones).
medicamento(fenogreco, extractos).
medicamento(fumaria, infusiones).
medicamento(fumaria, extractos).
medicamento(hierbabuena, aceite_esencial).
medicamento(hierbabuena, infusiones).
medicamento(jengibre, infusiones).
medicamento(jengibre, extractos).
medicamento(lavanda, aceite_esencial).
medicamento(lavanda, infusiones).
medicamento(naranjo, infusiones).
medicamento(naranjo, extractos).
medicamento(perejil, infusiones).
medicamento(perejil, extractos).
medicamento(sabila, gel).
medicamento(sabila, cremas).
medicamento(valeriana, infusiones).
medicamento(valeriana, extractos).

% Efectos de los medicamentos
efecto(ajo, antibacteriano).
efecto(ajo, antioxidante).
efecto(ajo, antiinflamatorio).
efecto(ajo, mejora_salud_cardiovascular).
efecto(ajo, refuerza_sistema_inmunologico).
efecto(borraja, antiinflamatorio).
efecto(borraja, diuretico).
efecto(borraja, expectorante).
efecto(borraja, sudorifico).
efecto(bugambilia, expectorante).
efecto(bugambilia, antitusivo).
efecto(bugambilia, antiinflamatorio).
efecto(bugambilia, antiseptico).
efecto(brionia_blanca, purgante).
efecto(brionia_blanca, expectorante).
efecto(brionia_blanca, antiinflamatorio).
efecto(brionia_blanca, analgesico).
efecto(ahuehuete, antiinflamatorio).
efecto(ahuehuete, diuretico).
efecto(ahuehuete, cicatrizante).
efecto(ajenjo, digestivo).
efecto(ajenjo, vermifugo).
efecto(ajenjo, antiinflamatorio).
efecto(ajenjo, tonico).
efecto(pasiflora, ansiolitico).
efecto(pasiflora, sedante).
efecto(pasiflora, antiespasmodico).
efecto(pasiflora, analgesico).
efecto(palo_de_flor, antiinflamatorio).
efecto(palo_de_flor, analgesico).
efecto(palo_de_flor, cicatrizante).
efecto(palo_de_flor, antiseptico).
efecto(oregano, antimicrobiano).
efecto(oregano, antioxidante).
efecto(oregano, antiinflamatorio).
efecto(oregano, digestivo).
efecto(oregano, antifungico).
efecto(ortiga, antiinflamatorio).
efecto(ortiga, diuretico).
efecto(ortiga, antialergico).
efecto(ortiga, estimulante_sistema_inmunologico).
efecto(anis_estrella, carminativo).
efecto(anis_estrella, expectorante).
efecto(anis_estrella, antiespasmódico).
efecto(menta, digestivo).
efecto(menta, refrescante).
efecto(arnica, antiinflamatorio).
efecto(arnica, analgésico).
efecto(salvia, antiinflamatorio).
efecto(salvia, antioxidante).
efecto(tila, sedante).
efecto(tila, calmante).
efecto(eucalipto, expectorante).
efecto(eucalipto, antiséptico).
efecto(yerbabuena, digestivo).
efecto(yerbabuena, refrescante).
efecto(manzanilla, antiinflamatorio).
efecto(manzanilla, digestivo).
efecto(cola_de_caballo, diurético).
efecto(cola_de_caballo, remineralizante).
efecto(romero, antiinflamatorio).
efecto(romero, antioxidante).
efecto(toronjil, calmante).
efecto(toronjil, antiespasmódico).
efecto(sanguinaria, expectorante).
efecto(sanguinaria, antiséptico).
efecto(linaza, antiinflamatorio).
efecto(linaza, digestivo).
efecto(hamamelis, astringente).
efecto(hamamelis, antiinflamatorio).
efecto(zarzaparrilla, depurativo).
efecto(zarzaparrilla, antiinflamatorio).
efecto(boldo, digestivo).
efecto(boldo, hepatoprotector).
efecto(diente_de_leon, diurético).
efecto(diente_de_leon, digestivo).
efecto(azahar, sedante).
efecto(azahar, digestivo).
efecto(malva, emoliente).
efecto(malva, antiinflamatorio).
efecto(marrubio, expectorante).
efecto(marrubio, digestivo).
efecto(rosal, antioxidante).
efecto(rosal, antiinflamatorio).
efecto(achicoria, depurativo).
efecto(alcachofa, hepatoprotector).
efecto(anis, digestivo).
efecto(canela, antimicrobiano).
efecto(cedron, sedante).
efecto(enebro, antirreumático).
efecto(fenogreco, antiinflamatorio).
efecto(fumaria, depurativo).
efecto(hierbabuena, digestivo).
efecto(jengibre, antiemético).
efecto(lavanda, relajante).
efecto(naranjo, calmante).
efecto(perejil, diurético).
efecto(sabila, cicatrizante).
efecto(valeriana, sedante).

% Enfermedades que cura
cura(ajo, hipertension).
cura(ajo, resfriado_comun).
cura(ajo, infecciones_bacterianas).
cura(ajo, colesterol_alto).
cura(borraja, artritis).
cura(borraja, problemas_respiratorios).
cura(borraja, fiebre).
cura(borraja, infecciones_del_tracto_urinario).
cura(bugambilia, tos).
cura(bugambilia, bronquitis).
cura(bugambilia, resfriados).
cura(bugambilia, infecciones_respiratorias).
cura(brionia_blanca, estrenimiento).
cura(brionia_blanca, problemas_respiratorios).
cura(brionia_blanca, dolores_articulares).
cura(brionia_blanca, reumatismo).
cura(ahuehuete, infecciones_urinarias).
cura(ahuehuete, heridas).
cura(ahuehuete, inflamaciones).
cura(ajenjo, problemas_digestivos).
cura(ajenjo, parasitos_intestinales).
cura(ajenjo, inflamaciones).
cura(ajenjo, fiebre).
cura(pasiflora, ansiedad).
cura(pasiflora, insomnio).
cura(pasiflora, espasmos_musculares).
cura(pasiflora, dolor).
cura(palo_de_flor, inflamaciones).
cura(palo_de_flor, dolores_musculares).
cura(palo_de_flor, heridas).
cura(palo_de_flor, infecciones_cutaneas).
cura(oregano, infecciones_respiratorias).
cura(oregano, problemas_digestivos).
cura(oregano, infecciones_fungicas).
cura(oregano, inflamaciones).
cura(ortiga, artritis).
cura(ortiga, alergias).
cura(ortiga, infecciones_urinarias).
cura(ortiga, anemia).
cura(anis_estrella, flatulencia).
cura(anis_estrella, tos).
cura(anis_estrella, cólicos).
cura(menta, indigestión).
cura(menta, náuseas).
cura(arnica, golpes).
cura(arnica, inflamaciones).
cura(salvia, resfriados).
cura(salvia, problemas_digestivos).
cura(tila, ansiedad).
cura(tila, insomnio).
cura(eucalipto, resfriados).
cura(eucalipto, bronquitis).
cura(yerbabuena, indigestión).
cura(yerbabuena, náuseas).
cura(manzanilla, indigestión).
cura(manzanilla, ansiedad).
cura(cola_de_caballo, retención_de_líquidos).
cura(cola_de_caballo, infecciones_urinarias).
cura(romero, problemas_digestivos).
cura(romero, dolor_muscular).
cura(toronjil, ansiedad).
cura(toronjil, indigestión).
cura(sanguinaria, resfriados).
cura(sanguinaria, bronquitis).
cura(linaza, estreñimiento).
cura(linaza, enfermedades_cardiovasculares).
cura(hamamelis, varices).
cura(hamamelis, hemorroides).
cura(zarzaparrilla, enfermedades_de_la_piel).
cura(zarzaparrilla, artritis).
cura(boldo, indigestión).
cura(boldo, enfermedades_del_hígado).
cura(diente_de_leon, retención_de_líquidos).
cura(diente_de_leon, problemas_digestivos).
cura(azahar, insomnio).
cura(azahar, problemas_digestivos).
cura(malva, irritaciones_gástricas).
cura(malva, inflamaciones_de_la_piel).
cura(marrubio, tos).
cura(marrubio, indigestión).
cura(rosal, resfriados).
cura(rosal, inflamaciones).
cura(achicoria, problemas_hepáticos).
cura(alcachofa, problemas_hepáticos).
cura(anis, indigestión).
cura(canela, infecciones).
cura(cedron, ansiedad).
cura(enebro, artritis).
cura(fenogreco, inflamación).
cura(fumaria, eczema).
cura(hierbabuena, indigestión).
cura(jengibre, náuseas).
cura(lavanda, estrés).
cura(naranjo, insomnio).
cura(perejil, retención_de_líquidos).
cura(sabila, quemaduras).
cura(valeriana, insomnio).

% Modos de preparación
preparacion(ajo, crudo).
preparacion(ajo, en_aceite).
preparacion(ajo, en_extracto).
preparacion(ajo, en_capsulas).
preparacion(borraja, infusion).
preparacion(borraja, aceite_esencial).
preparacion(borraja, extracto).
preparacion(borraja, en_capsulas).
preparacion(bugambilia, infusion).
preparacion(bugambilia, jarabe).
preparacion(bugambilia, extracto).
preparacion(brionia_blanca, infusion).
preparacion(brionia_blanca, extracto).
preparacion(brionia_blanca, tintura).
preparacion(brionia_blanca, unguento).
preparacion(ahuehuete, infusion).
preparacion(ahuehuete, extracto).
preparacion(ahuehuete, unguento).
preparacion(ajenjo, infusion).
preparacion(ajenjo, extracto).
preparacion(ajenjo, tintura).
preparacion(pasiflora, infusion).
preparacion(pasiflora, extracto).
preparacion(pasiflora, en_capsulas).
preparacion(palo_de_flor, infusion).
preparacion(palo_de_flor, aceite_esencial).
preparacion(palo_de_flor, extracto).
preparacion(palo_de_flor, unguento).
preparacion(oregano, infusion).
preparacion(oregano, aceite_esencial).
preparacion(oregano, extracto).
preparacion(oregano, en_capsulas).
preparacion(ortiga, infusion).
preparacion(ortiga, extracto).
preparacion(ortiga, en_capsulas).
preparacion(ortiga, en_cremas).
preparacion(anis_estrella, infusion).
preparacion(anis_estrella, extracto).
preparacion(anis_estrella, en_aceite).
preparacion(menta, infusion).
preparacion(menta, aceite).
preparacion(arnica, pomada).
preparacion(arnica, en_infusión).
preparacion(salvia, infusion).
preparacion(salvia, extracto).
preparacion(tila, infusion).
preparacion(tila, extracto).
preparacion(eucalipto, infusion).
preparacion(eucalipto, aceite).
preparacion(yerbabuena, infusion).
preparacion(yerbabuena, aceite).
preparacion(manzanilla, infusion).
preparacion(manzanilla, extracto).
preparacion(cola_de_caballo, infusion).
preparacion(cola_de_caballo, extracto).
preparacion(romero, infusion).
preparacion(romero, aceite).
preparacion(toronjil, infusion).
preparacion(toronjil, extracto).
preparacion(sanguinaria, extracto).
preparacion(sanguinaria, tintura).
preparacion(linaza, aceite).
preparacion(linaza, suplemento).
preparacion(hamamelis, extracto).
preparacion(hamamelis, crema).
preparacion(zarzaparrilla, infusion).
preparacion(zarzaparrilla, extracto).
preparacion(boldo, infusion).
preparacion(boldo, extracto).
preparacion(diente_de_leon, infusion).
preparacion(diente_de_leon, extracto).
preparacion(azahar, infusion).
preparacion(azahar, extracto).
preparacion(malva, infusion).
preparacion(malva, extracto).
preparacion(marrubio, infusion).
preparacion(marrubio, extracto).
preparacion(rosal, infusion).
preparacion(rosal, extracto).
preparacion(achicoria, infusion).
preparacion(alcachofa, infusion).
preparacion(anis, infusion).
preparacion(canela, infusion).
preparacion(cedron, infusion).
preparacion(enebro, infusion).
preparacion(fenogreco, infusion).
preparacion(fumaria, infusion).
preparacion(hierbabuena, infusion).
preparacion(jengibre, infusion).
preparacion(lavanda, aceite).
preparacion(naranjo, infusion).
preparacion(perejil, infusion).
preparacion(sabila, tópica).

% Origen
origen(ajo, asia_central).
origen(borraja, region_mediterranea).
origen(bugambilia, america_del_sur).
origen(brionia_blanca, europa_y_asia_occidental).
origen(ahuehuete, mexico_y_america_central).
origen(ajenjo, europa_asia_y_norte_de_africa).
origen(pasiflora, america_del_norte_y_del_sur).
origen(palo_de_flor, mexico_y_america_central).
origen(oregano, region_del_mediterraneo).
origen(ortiga, europa_y_asia).
origen(anis_estrella, asia).
origen(menta, europa).
origen(arnica, europa).
origen(salv
